name: Release

on:
  push:
    branches:
      - master-0.2

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.repository_owner == 'WaterBearSondes'
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: npm clean install
        run: npm i
        working-directory: ${{ env.project-directory }}
        
      - run: npm i -g semantic-release @semantic-release/{git,exec,changelog}
      
      - run: semantic-release
        working-directory: ${{ env.project-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          
        
